# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
from numpy import dtype
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
import numpy as np
empty = np.empty((3,2))
print(empty)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.42420617e-306]
 [1.89146896e-307 7.56571288e-307]]


#### 4. How to find the memory size of any array (★☆☆)

In [15]:
import numpy as np
array = np.array([[1,2],[3,4],[5,6]],dtype=float)
print(array)
print(array.itemsize)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [26]:
print(np.add([1,2,3],[4,5,6]))

[5 7 9]


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [27]:
import numpy as np
one_as_axis = np.eye(10,10,0,dtype=int)
print(one_as_axis)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
ranged_array = np.arange(10,49,4,dtype=int)
print(ranged_array)

[10 14 18 22 26 30 34 38 42 46]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [30]:
array_to_reverse = np.array([1,2,3,4,5,6,7,8,9])
print(array_to_reverse[::-1])

[9 8 7 6 5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
ranged_array = np.arange(0,9,dtype=int).reshape(3,3)
print(ranged_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [8]:
sample = [1,2,0,0,4,0]
for i in sample:
    print(sample.index(i))

0
1
2
2
4
2


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
import numpy as np
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
import numpy as np
randoms = np.random.random((3,3,3))
randoms

array([[[0.59738017, 0.07853839, 0.23623247],
        [0.03134187, 0.62566589, 0.99387604],
        [0.3671115 , 0.39127614, 0.80264341]],

       [[0.98343252, 0.62312329, 0.42171107],
        [0.42227918, 0.71069195, 0.82443339],
        [0.78090933, 0.7621415 , 0.59718411]],

       [[0.93073168, 0.70335668, 0.10449287],
        [0.7002796 , 0.72357165, 0.34328033],
        [0.96775338, 0.48004736, 0.030884  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
import numpy as np
array = np.random.random((10,10))
max = array.max()
min = array.min()
print(max)
print(min)

0.9870392820945116
0.024834082247303213


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
import numpy as np
arr = np.random.random((10,3))
mean = np.mean(arr)
mean

np.float64(0.44557785242189313)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
import numpy as np
two_D_array = np.eye(2)
print(two_D_array)

[[1. 0.]
 [0. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [39]:
import numpy as np
sample_array = np.full((10,10),2)
sample_array[0, :] = 0
sample_array[-1, :] = 0
sample_array[:, 0] = 0
sample_array[:, -1] = 0  
print(sample_array)

[[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 2 2 2 2 2 2 2 2 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [53]:
import numpy as np
five_by_five_array = np.full((5,5),0,dtype=int)
for i in range(0,4):
    five_by_five_array[i+1,i] = i+1
print(five_by_five_array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [148]:
import numpy as np
size = 9
if size%2 != 0:
    eight_by_eight = np.full((size,size),"_",dtype=np.str_)
    for i in range(0,size):
        for j in range(i+1,size):
            eight_by_eight[j,i] = "*"
    for i in range(0,size):
        for j in range(i+1,size):
            eight_by_eight[i,j] = "*"
    print(eight_by_eight)

[['_' '*' '*' '*' '*' '*' '*' '*' '*']
 ['*' '_' '*' '*' '*' '*' '*' '*' '*']
 ['*' '*' '_' '*' '*' '*' '*' '*' '*']
 ['*' '*' '*' '_' '*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '_' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*' '_' '*' '*' '*']
 ['*' '*' '*' '*' '*' '*' '_' '*' '*']
 ['*' '*' '*' '*' '*' '*' '*' '_' '*']
 ['*' '*' '*' '*' '*' '*' '*' '*' '_']]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [156]:
import numpy as np
custom_array = np.full((6,7,8),5,dtype=int)
index = 0
custom_array[1,5,3] = 50
for x in range(0,6):
    for y in range(0,7):
        for z in range(0,8):
            index=index+1
            if index == 100:
                print(index)
                print(x,y,z)
                print(custom_array[x,y,z])

100
1 5 3
50



#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [169]:
simple_array = np.array([1,2,3,4,5,6,7,8])
tile_array = np.tile(simple_array,(8,1))
print(tile_array)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [170]:
random_array = np.random.random((5,5))
print(random_array)

[[0.63999737 0.22364532 0.60873113 0.05120109 0.04047021]
 [0.79239776 0.73800131 0.13271342 0.09031784 0.67883924]
 [0.15222077 0.32871036 0.69729434 0.11320852 0.68867484]
 [0.20409374 0.42998191 0.72398543 0.6060834  0.62808784]
 [0.50495599 0.94237716 0.18592455 0.32492045 0.17252325]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [179]:
red=int(np.random.random((1,1))[0][0]*255)
green=int(np.random.random((1,1))[0][0]*255)
blue=int(np.random.random((1,1))[0][0]*255)
rgba = np.array([red,green,blue,np.random.random((1,1))[0][0]])
print(rgba)

[235.         183.         189.           0.34677613]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [186]:
array1 = np.random.random((5,3))
array2 = np.random.random((3,2))
l1,c1 = array1.shape
l2,c2 = array2.shape
sum_array = []
if c1 == l2:
    for i in range(c2):
        numbers_sum_x = 0
        for j in range(l1):
            numbers_sum_x+=array1[i,j]*array2[i,j]
            sum_array.append(numbers_sum_x)
# if l1 == c2:
#     numbers_sum_x = 0
#     numbers_sum_y = 0
#     for i in range(c1):
#         pass
#         for j in range(l2):
#             pass
print(sum_array)

IndexError: index 2 is out of bounds for axis 1 with size 2

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)